// 전국 행정구역 데이터 (거주지역 검색용) — 시·군·구 단위
// 광역시/특별시: 산하 구·군 / 도: 시(구 있으면 구까지)·군 / 세종: 단일

export interface RegionOption {
  label: string;
  value: string;
}

// 광역시·특별시 → 산하 구·군 (세종은 구 없음 → 빈 배열)
const METRO: Record<string, string[]> = {
  서울특별시: [
    '종로구',
    '중구',
    '용산구',
    '성동구',
    '광진구',
    '동대문구',
    '중랑구',
    '성북구',
    '강북구',
    '도봉구',
    '노원구',
    '은평구',
    '서대문구',
    '마포구',
    '양천구',
    '강서구',
    '구로구',
    '금천구',
    '영등포구',
    '동작구',
    '관악구',
    '서초구',
    '강남구',
    '송파구',
    '강동구',
  ],
  부산광역시: [
    '중구',
    '서구',
    '동구',
    '영도구',
    '부산진구',
    '동래구',
    '남구',
    '북구',
    '해운대구',
    '사하구',
    '금정구',
    '강서구',
    '연제구',
    '수영구',
    '사상구',
    '기장군',
  ],
  대구광역시: ['중구', '동구', '서구', '남구', '북구', '수성구', '달서구', '달성군', '군위군'],
  인천광역시: [
    '중구',
    '동구',
    '미추홀구',
    '연수구',
    '남동구',
    '부평구',
    '계양구',
    '서구',
    '강화군',
    '옹진군',
  ],
  광주광역시: ['동구', '서구', '남구', '북구', '광산구'],
  대전광역시: ['동구', '중구', '서구', '유성구', '대덕구'],
  울산광역시: ['중구', '남구', '동구', '북구', '울주군'],
  세종특별자치시: [], // 구 없음 → 자신만
};

// 도 → 시(구 있으면 구까지)·군
type City = { name: string; districts?: string[] };
const PROVINCES: Record<string, City[]> = {
  경기도: [
    { name: '수원시', districts: ['장안구', '권선구', '팔달구', '영통구'] },
    { name: '성남시', districts: ['수정구', '중원구', '분당구'] },
    { name: '고양시', districts: ['덕양구', '일산동구', '일산서구'] },
    { name: '용인시', districts: ['처인구', '기흥구', '수지구'] },
    { name: '안산시', districts: ['상록구', '단원구'] },
    { name: '안양시', districts: ['만안구', '동안구'] },
    { name: '부천시' },
    { name: '화성시' },
    { name: '남양주시' },
    { name: '평택시' },
    { name: '시흥시' },
    { name: '파주시' },
    { name: '김포시' },
    { name: '광명시' },
    { name: '광주시' },
    { name: '군포시' },
    { name: '의정부시' },
    { name: '하남시' },
    { name: '오산시' },
    { name: '양주시' },
    { name: '이천시' },
    { name: '구리시' },
    { name: '안성시' },
    { name: '포천시' },
    { name: '의왕시' },
    { name: '여주시' },
    { name: '동두천시' },
    { name: '과천시' },
    { name: '양평군' },
    { name: '가평군' },
    { name: '연천군' },
  ],
  강원특별자치도: [
    { name: '춘천시' },
    { name: '원주시' },
    { name: '강릉시' },
    { name: '동해시' },
    { name: '태백시' },
    { name: '속초시' },
    { name: '삼척시' },
    { name: '홍천군' },
    { name: '횡성군' },
    { name: '영월군' },
    { name: '평창군' },
    { name: '정선군' },
    { name: '철원군' },
    { name: '화천군' },
    { name: '양구군' },
    { name: '인제군' },
    { name: '고성군' },
    { name: '양양군' },
  ],
  충청북도: [
    { name: '청주시', districts: ['상당구', '서원구', '흥덕구', '청원구'] },
    { name: '충주시' },
    { name: '제천시' },
    { name: '보은군' },
    { name: '옥천군' },
    { name: '영동군' },
    { name: '증평군' },
    { name: '진천군' },
    { name: '괴산군' },
    { name: '음성군' },
    { name: '단양군' },
  ],
  충청남도: [
    { name: '천안시', districts: ['동남구', '서북구'] },
    { name: '공주시' },
    { name: '보령시' },
    { name: '아산시' },
    { name: '서산시' },
    { name: '논산시' },
    { name: '계룡시' },
    { name: '당진시' },
    { name: '금산군' },
    { name: '부여군' },
    { name: '서천군' },
    { name: '청양군' },
    { name: '홍성군' },
    { name: '예산군' },
    { name: '태안군' },
  ],
  전북특별자치도: [
    { name: '전주시', districts: ['완산구', '덕진구'] },
    { name: '군산시' },
    { name: '익산시' },
    { name: '정읍시' },
    { name: '남원시' },
    { name: '김제시' },
    { name: '완주군' },
    { name: '진안군' },
    { name: '무주군' },
    { name: '장수군' },
    { name: '임실군' },
    { name: '순창군' },
    { name: '고창군' },
    { name: '부안군' },
  ],
  전라남도: [
    { name: '목포시' },
    { name: '여수시' },
    { name: '순천시' },
    { name: '나주시' },
    { name: '광양시' },
    { name: '담양군' },
    { name: '곡성군' },
    { name: '구례군' },
    { name: '고흥군' },
    { name: '보성군' },
    { name: '화순군' },
    { name: '장흥군' },
    { name: '강진군' },
    { name: '해남군' },
    { name: '영암군' },
    { name: '무안군' },
    { name: '함평군' },
    { name: '영광군' },
    { name: '장성군' },
    { name: '완도군' },
    { name: '진도군' },
    { name: '신안군' },
  ],
  경상북도: [
    { name: '포항시', districts: ['남구', '북구'] },
    { name: '경주시' },
    { name: '김천시' },
    { name: '안동시' },
    { name: '구미시' },
    { name: '영주시' },
    { name: '영천시' },
    { name: '상주시' },
    { name: '문경시' },
    { name: '경산시' },
    { name: '의성군' },
    { name: '청송군' },
    { name: '영양군' },
    { name: '영덕군' },
    { name: '청도군' },
    { name: '고령군' },
    { name: '성주군' },
    { name: '칠곡군' },
    { name: '예천군' },
    { name: '봉화군' },
    { name: '울진군' },
    { name: '울릉군' },
  ],
  경상남도: [
    { name: '창원시', districts: ['의창구', '성산구', '마산합포구', '마산회원구', '진해구'] },
    { name: '진주시' },
    { name: '통영시' },
    { name: '사천시' },
    { name: '김해시' },
    { name: '밀양시' },
    { name: '거제시' },
    { name: '양산시' },
    { name: '의령군' },
    { name: '함안군' },
    { name: '창녕군' },
    { name: '고성군' },
    { name: '남해군' },
    { name: '하동군' },
    { name: '산청군' },
    { name: '함양군' },
    { name: '거창군' },
    { name: '합천군' },
  ],
  제주특별자치도: [{ name: '제주시' }, { name: '서귀포시' }],
};

export const REGION_OPTIONS: RegionOption[] = [
  // 광역시/특별시: 구·군이 있으면 "시 구", 없으면(세종) 자신만
  ...Object.entries(METRO).flatMap(([metro, districts]) =>
    districts.length === 0
      ? [{ label: metro, value: metro }]
      : districts.map((d) => ({ label: `${metro} ${d}`, value: `${metro} ${d}` })),
  ),
  // 도: 구가 있으면 "도 시 구", 없으면 "도 시" / 군은 "도 군"
  ...Object.entries(PROVINCES).flatMap(([province, cities]) =>
    cities.flatMap((city) =>
      city.districts
        ? city.districts.map((d) => ({
            label: `${province} ${city.name} ${d}`,
            value: `${province} ${city.name} ${d}`,
          }))
        : [{ label: `${province} ${city.name}`, value: `${province} ${city.name}` }],
    ),
  ),
];
