// 전국 대학 목록 (교육부 학교개황 기준 · 대학원 제외 · 캠퍼스 구분)
// 거주지역과 동일한 SearchableSelect에서 사용

export interface UniversityOption {
  label: string;
  value: string;
}

export const UNIVERSITY_OPTIONS: UniversityOption[] = [
  { label: 'ICT폴리텍대학', value: 'ICT폴리텍대학' },
  { label: '가야대학교 (고령)', value: '가야대학교 (고령)' },
  { label: '가야대학교 (김해)', value: '가야대학교 (김해)' },
  { label: '가천대학교', value: '가천대학교' },
  { label: '가톨릭관동대학교', value: '가톨릭관동대학교' },
  { label: '가톨릭꽃동네대학교', value: '가톨릭꽃동네대학교' },
  { label: '가톨릭대학교 (부천)', value: '가톨릭대학교 (부천)' },
  { label: '가톨릭대학교 (서울)', value: '가톨릭대학교 (서울)' },
  { label: '가톨릭상지대학교', value: '가톨릭상지대학교' },
  { label: '감리교신학대학교', value: '감리교신학대학교' },
  { label: '강남대학교', value: '강남대학교' },
  { label: '강동대학교', value: '강동대학교' },
  { label: '강릉영동대학교', value: '강릉영동대학교' },
  { label: '강서대학교', value: '강서대학교' },
  { label: '강원대학교 (삼척)', value: '강원대학교 (삼척)' },
  { label: '강원대학교 (춘천)', value: '강원대학교 (춘천)' },
  { label: '강원도립대학교', value: '강원도립대학교' },
  { label: '거제대학교', value: '거제대학교' },
  { label: '건국대학교', value: '건국대학교' },
  { label: '건국대학교 (글로컬)', value: '건국대학교 (글로컬)' },
  { label: '건양대학교 (논산)', value: '건양대학교 (논산)' },
  { label: '건양대학교 (대전)', value: '건양대학교 (대전)' },
  { label: '건양사이버대학교', value: '건양사이버대학교' },
  { label: '경기과학기술대학교', value: '경기과학기술대학교' },
  { label: '경기대학교 (서울)', value: '경기대학교 (서울)' },
  { label: '경기대학교 (수원)', value: '경기대학교 (수원)' },
  { label: '경남대학교', value: '경남대학교' },
  { label: '경남도립거창대학', value: '경남도립거창대학' },
  { label: '경남도립남해대학', value: '경남도립남해대학' },
  { label: '경남정보대학교', value: '경남정보대학교' },
  { label: '경동대학교 (고성)', value: '경동대학교 (고성)' },
  { label: '경동대학교 (속초)', value: '경동대학교 (속초)' },
  { label: '경동대학교 (양주)', value: '경동대학교 (양주)' },
  { label: '경동대학교 (원주)', value: '경동대학교 (원주)' },
  { label: '경민대학교', value: '경민대학교' },
  { label: '경복대학교', value: '경복대학교' },
  { label: '경북과학대학교', value: '경북과학대학교' },
  { label: '경북대학교', value: '경북대학교' },
  { label: '경북도립대학교', value: '경북도립대학교' },
  { label: '경북보건대학교', value: '경북보건대학교' },
  { label: '경북전문대학교', value: '경북전문대학교' },
  { label: '경상국립대학교', value: '경상국립대학교' },
  { label: '경성대학교', value: '경성대학교' },
  { label: '경운대학교', value: '경운대학교' },
  { label: '경인교육대학교 (안양)', value: '경인교육대학교 (안양)' },
  { label: '경인교육대학교 (인천)', value: '경인교육대학교 (인천)' },
  { label: '경인여자대학교', value: '경인여자대학교' },
  { label: '경일대학교', value: '경일대학교' },
  { label: '경희대학교', value: '경희대학교' },
  { label: '경희사이버대학교', value: '경희사이버대학교' },
  { label: '계명대학교', value: '계명대학교' },
  { label: '계명문화대학교', value: '계명문화대학교' },
  { label: '계원예술대학교', value: '계원예술대학교' },
  { label: '고려대학교', value: '고려대학교' },
  { label: '고려대학교 (세종)', value: '고려대학교 (세종)' },
  { label: '고려사이버대학교', value: '고려사이버대학교' },
  { label: '고신대학교', value: '고신대학교' },
  { label: '공주교육대학교', value: '공주교육대학교' },
  { label: '광신대학교', value: '광신대학교' },
  { label: '광양보건대학교', value: '광양보건대학교' },
  { label: '광운대학교', value: '광운대학교' },
  { label: '광주가톨릭대학교', value: '광주가톨릭대학교' },
  { label: '광주과학기술원', value: '광주과학기술원' },
  { label: '광주교육대학교', value: '광주교육대학교' },
  { label: '광주대학교', value: '광주대학교' },
  { label: '광주보건대학교', value: '광주보건대학교' },
  { label: '광주여자대학교', value: '광주여자대학교' },
  { label: '구미대학교', value: '구미대학교' },
  { label: '국립강릉원주대학교 (강릉)', value: '국립강릉원주대학교 (강릉)' },
  { label: '국립강릉원주대학교 (원주)', value: '국립강릉원주대학교 (원주)' },
  { label: '국립공주대학교', value: '국립공주대학교' },
  { label: '국립군산대학교', value: '국립군산대학교' },
  { label: '국립금오공과대학교', value: '국립금오공과대학교' },
  { label: '국립목포대학교', value: '국립목포대학교' },
  { label: '국립목포해양대학교', value: '국립목포해양대학교' },
  { label: '국립부경대학교', value: '국립부경대학교' },
  { label: '국립순천대학교', value: '국립순천대학교' },
  { label: '국립안동대학교', value: '국립안동대학교' },
  { label: '국립창원대학교', value: '국립창원대학교' },
  { label: '국립한국교통대학교', value: '국립한국교통대학교' },
  { label: '국립한국해양대학교', value: '국립한국해양대학교' },
  { label: '국립한밭대학교', value: '국립한밭대학교' },
  { label: '국민대학교', value: '국민대학교' },
  { label: '국제대학교', value: '국제대학교' },
  { label: '국제사이버대학교', value: '국제사이버대학교' },
  { label: '군산간호대학교', value: '군산간호대학교' },
  { label: '군장대학교', value: '군장대학교' },
  { label: '극동대학교', value: '극동대학교' },
  { label: '글로벌사이버대학교', value: '글로벌사이버대학교' },
  { label: '금강대학교', value: '금강대학교' },
  { label: '기독간호대학교', value: '기독간호대학교' },
  { label: '김천대학교', value: '김천대학교' },
  { label: '김포대학교', value: '김포대학교' },
  { label: '김해대학교', value: '김해대학교' },
  { label: '나사렛대학교', value: '나사렛대학교' },
  { label: '나주대학교', value: '나주대학교' },
  { label: '남부대학교', value: '남부대학교' },
  { label: '남서울대학교', value: '남서울대학교' },
  { label: '농협대학교', value: '농협대학교' },
  { label: '단국대학교 (용인)', value: '단국대학교 (용인)' },
  { label: '단국대학교 (천안)', value: '단국대학교 (천안)' },
  { label: '대경대학교', value: '대경대학교' },
  { label: '대구가톨릭대학교', value: '대구가톨릭대학교' },
  { label: '대구경북과학기술원', value: '대구경북과학기술원' },
  { label: '대구공업대학교', value: '대구공업대학교' },
  { label: '대구과학대학교', value: '대구과학대학교' },
  { label: '대구교육대학교', value: '대구교육대학교' },
  { label: '대구대학교', value: '대구대학교' },
  { label: '대구보건대학교', value: '대구보건대학교' },
  { label: '대구사이버대학교', value: '대구사이버대학교' },
  { label: '대구예술대학교', value: '대구예술대학교' },
  { label: '대구한의대학교', value: '대구한의대학교' },
  { label: '대덕대학교', value: '대덕대학교' },
  { label: '대동대학교', value: '대동대학교' },
  { label: '대림대학교', value: '대림대학교' },
  { label: '대신대학교', value: '대신대학교' },
  { label: '대원대학교', value: '대원대학교' },
  { label: '대전가톨릭대학교', value: '대전가톨릭대학교' },
  { label: '대전과학기술대학교', value: '대전과학기술대학교' },
  { label: '대전대학교', value: '대전대학교' },
  { label: '대전보건대학교', value: '대전보건대학교' },
  { label: '대전신학대학교', value: '대전신학대학교' },
  { label: '대진대학교', value: '대진대학교' },
  { label: '덕성여자대학교', value: '덕성여자대학교' },
  { label: '동강대학교', value: '동강대학교' },
  { label: '동국대학교', value: '동국대학교' },
  { label: '동국대학교 (WISE)', value: '동국대학교 (WISE)' },
  { label: '동남보건대학교', value: '동남보건대학교' },
  { label: '동덕여자대학교', value: '동덕여자대학교' },
  { label: '동명대학교', value: '동명대학교' },
  { label: '동서대학교', value: '동서대학교' },
  { label: '동서울대학교', value: '동서울대학교' },
  { label: '동신대학교', value: '동신대학교' },
  { label: '동아대학교', value: '동아대학교' },
  { label: '동아방송예술대학교', value: '동아방송예술대학교' },
  { label: '동아보건대학교', value: '동아보건대학교' },
  { label: '동양대학교', value: '동양대학교' },
  { label: '동양미래대학교', value: '동양미래대학교' },
  { label: '동원과학기술대학교', value: '동원과학기술대학교' },
  { label: '동원대학교', value: '동원대학교' },
  { label: '동의과학대학교', value: '동의과학대학교' },
  { label: '동의대학교', value: '동의대학교' },
  { label: '두원공과대학교', value: '두원공과대학교' },
  { label: '디지털서울문화예술대학교', value: '디지털서울문화예술대학교' },
  { label: '루터대학교', value: '루터대학교' },
  { label: '마산대학교', value: '마산대학교' },
  { label: '명지대학교 (서울)', value: '명지대학교 (서울)' },
  { label: '명지대학교 (용인)', value: '명지대학교 (용인)' },
  { label: '명지전문대학', value: '명지전문대학' },
  { label: '목원대학교', value: '목원대학교' },
  { label: '목포가톨릭대학교', value: '목포가톨릭대학교' },
  { label: '목포과학대학교', value: '목포과학대학교' },
  { label: '문경대학교', value: '문경대학교' },
  { label: '배재대학교', value: '배재대학교' },
  { label: '배화여자대학교', value: '배화여자대학교' },
  { label: '백석대학교', value: '백석대학교' },
  { label: '백석문화대학교', value: '백석문화대학교' },
  { label: '백제예술대학교', value: '백제예술대학교' },
  { label: '부산가톨릭대학교', value: '부산가톨릭대학교' },
  { label: '부산경상대학교', value: '부산경상대학교' },
  { label: '부산과학기술대학교', value: '부산과학기술대학교' },
  { label: '부산교육대학교', value: '부산교육대학교' },
  { label: '부산대학교', value: '부산대학교' },
  { label: '부산디지털대학교', value: '부산디지털대학교' },
  { label: '부산보건대학교', value: '부산보건대학교' },
  { label: '부산여자대학교', value: '부산여자대학교' },
  { label: '부산예술대학교', value: '부산예술대학교' },
  { label: '부산외국어대학교', value: '부산외국어대학교' },
  { label: '부산장신대학교', value: '부산장신대학교' },
  { label: '부천대학교', value: '부천대학교' },
  { label: '사이버한국외국어대학교', value: '사이버한국외국어대학교' },
  { label: '삼육대학교', value: '삼육대학교' },
  { label: '삼육보건대학교', value: '삼육보건대학교' },
  { label: '상명대학교 (서울)', value: '상명대학교 (서울)' },
  { label: '상명대학교 (천안)', value: '상명대학교 (천안)' },
  { label: '상지대학교', value: '상지대학교' },
  { label: '서강대학교', value: '서강대학교' },
  { label: '서경대학교', value: '서경대학교' },
  { label: '서영대학교', value: '서영대학교' },
  { label: '서울과학기술대학교', value: '서울과학기술대학교' },
  { label: '서울교육대학교', value: '서울교육대학교' },
  { label: '서울기독대학교', value: '서울기독대학교' },
  { label: '서울대학교', value: '서울대학교' },
  { label: '서울디지털대학교', value: '서울디지털대학교' },
  { label: '서울사이버대학교', value: '서울사이버대학교' },
  { label: '서울시립대학교', value: '서울시립대학교' },
  { label: '서울신학대학교', value: '서울신학대학교' },
  { label: '서울여자간호대학교', value: '서울여자간호대학교' },
  { label: '서울여자대학교', value: '서울여자대학교' },
  { label: '서울예술대학교', value: '서울예술대학교' },
  { label: '서울장신대학교', value: '서울장신대학교' },
  { label: '서울한영대학교', value: '서울한영대학교' },
  { label: '서원대학교', value: '서원대학교' },
  { label: '서일대학교', value: '서일대학교' },
  { label: '서정대학교', value: '서정대학교' },
  { label: '선린대학교', value: '선린대학교' },
  { label: '선문대학교', value: '선문대학교' },
  { label: '성결대학교', value: '성결대학교' },
  { label: '성공회대학교', value: '성공회대학교' },
  { label: '성균관대학교', value: '성균관대학교' },
  { label: '성신여자대학교', value: '성신여자대학교' },
  { label: '성운대학교', value: '성운대학교' },
  { label: '세경대학교', value: '세경대학교' },
  { label: '세명대학교', value: '세명대학교' },
  { label: '세종대학교', value: '세종대학교' },
  { label: '세종사이버대학교', value: '세종사이버대학교' },
  { label: '세한대학교', value: '세한대학교' },
  { label: '송곡대학교', value: '송곡대학교' },
  { label: '송원대학교', value: '송원대학교' },
  { label: '송호대학교', value: '송호대학교' },
  { label: '수성대학교', value: '수성대학교' },
  { label: '수원가톨릭대학교', value: '수원가톨릭대학교' },
  { label: '수원과학대학교', value: '수원과학대학교' },
  { label: '수원대학교', value: '수원대학교' },
  { label: '수원여자대학교', value: '수원여자대학교' },
  { label: '숙명여자대학교', value: '숙명여자대학교' },
  { label: '순복음총회신학교', value: '순복음총회신학교' },
  { label: '순천제일대학교', value: '순천제일대학교' },
  { label: '순천향대학교', value: '순천향대학교' },
  { label: '숭실대학교', value: '숭실대학교' },
  { label: '숭실사이버대학교', value: '숭실사이버대학교' },
  { label: '숭의여자대학교', value: '숭의여자대학교' },
  { label: '신경주대학교', value: '신경주대학교' },
  { label: '신구대학교', value: '신구대학교' },
  { label: '신라대학교', value: '신라대학교' },
  { label: '신성대학교', value: '신성대학교' },
  { label: '신안산대학교', value: '신안산대학교' },
  { label: '신한대학교 (동두천)', value: '신한대학교 (동두천)' },
  { label: '신한대학교 (의정부)', value: '신한대학교 (의정부)' },
  { label: '아신대학교', value: '아신대학교' },
  { label: '아주대학교', value: '아주대학교' },
  { label: '아주자동차대학교', value: '아주자동차대학교' },
  { label: '안동과학대학교', value: '안동과학대학교' },
  { label: '안산대학교', value: '안산대학교' },
  { label: '안양대학교 (안양)', value: '안양대학교 (안양)' },
  { label: '안양대학교 (인천)', value: '안양대학교 (인천)' },
  { label: '여주대학교', value: '여주대학교' },
  { label: '연성대학교', value: '연성대학교' },
  { label: '연세대학교', value: '연세대학교' },
  { label: '연세대학교 (미래)', value: '연세대학교 (미래)' },
  { label: '연암공과대학교', value: '연암공과대학교' },
  { label: '연암대학교', value: '연암대학교' },
  { label: '영남대학교', value: '영남대학교' },
  { label: '영남신학대학교', value: '영남신학대학교' },
  { label: '영남외국어대학', value: '영남외국어대학' },
  { label: '영남이공대학교', value: '영남이공대학교' },
  { label: '영산대학교 (양산)', value: '영산대학교 (양산)' },
  { label: '영산대학교 (해운대)', value: '영산대학교 (해운대)' },
  { label: '영산선학대학교', value: '영산선학대학교' },
  { label: '영진사이버대학교', value: '영진사이버대학교' },
  { label: '영진전문대학교', value: '영진전문대학교' },
  { label: '예수대학교', value: '예수대학교' },
  { label: '예원예술대학교 (양주)', value: '예원예술대학교 (양주)' },
  { label: '예원예술대학교 (임실)', value: '예원예술대학교 (임실)' },
  { label: '오산대학교', value: '오산대학교' },
  { label: '용인대학교', value: '용인대학교' },
  { label: '용인예술과학대학교', value: '용인예술과학대학교' },
  { label: '우석대학교', value: '우석대학교' },
  { label: '우송대학교', value: '우송대학교' },
  { label: '우송정보대학', value: '우송정보대학' },
  { label: '울산과학기술원', value: '울산과학기술원' },
  { label: '울산과학대학교', value: '울산과학대학교' },
  { label: '울산대학교', value: '울산대학교' },
  { label: '웅지세무대학교', value: '웅지세무대학교' },
  { label: '원광대학교', value: '원광대학교' },
  { label: '원광디지털대학교', value: '원광디지털대학교' },
  { label: '원광보건대학교', value: '원광보건대학교' },
  { label: '위덕대학교', value: '위덕대학교' },
  { label: '유원대학교', value: '유원대학교' },
  { label: '유한대학교', value: '유한대학교' },
  { label: '을지대학교 (대전)', value: '을지대학교 (대전)' },
  { label: '을지대학교 (성남)', value: '을지대학교 (성남)' },
  { label: '을지대학교 (의정부)', value: '을지대학교 (의정부)' },
  { label: '이화여자대학교', value: '이화여자대학교' },
  { label: '인덕대학교', value: '인덕대학교' },
  { label: '인제대학교 (김해)', value: '인제대학교 (김해)' },
  { label: '인제대학교 (부산)', value: '인제대학교 (부산)' },
  { label: '인천가톨릭대학교 (인천)', value: '인천가톨릭대학교 (인천)' },
  { label: '인천대학교', value: '인천대학교' },
  { label: '인하공업전문대학', value: '인하공업전문대학' },
  { label: '인하대학교', value: '인하대학교' },
  { label: '장로회신학대학교', value: '장로회신학대학교' },
  { label: '장안대학교', value: '장안대학교' },
  { label: '재능대학교', value: '재능대학교' },
  { label: '전남과학대학교', value: '전남과학대학교' },
  { label: '전남대학교 (광주)', value: '전남대학교 (광주)' },
  { label: '전남대학교 (여수)', value: '전남대학교 (여수)' },
  { label: '전남도립대학교', value: '전남도립대학교' },
  { label: '전북과학대학교', value: '전북과학대학교' },
  { label: '전북대학교', value: '전북대학교' },
  { label: '전주교육대학교', value: '전주교육대학교' },
  { label: '전주기전대학', value: '전주기전대학' },
  { label: '전주대학교', value: '전주대학교' },
  { label: '전주비전대학교', value: '전주비전대학교' },
  { label: '정석대학', value: '정석대학' },
  { label: '제주관광대학교', value: '제주관광대학교' },
  { label: '제주국제대학교', value: '제주국제대학교' },
  { label: '제주대학교', value: '제주대학교' },
  { label: '제주한라대학교', value: '제주한라대학교' },
  { label: '조선간호대학교', value: '조선간호대학교' },
  { label: '조선대학교', value: '조선대학교' },
  { label: '조선이공대학교', value: '조선이공대학교' },
  { label: '중부대학교', value: '중부대학교' },
  { label: '중앙대학교 (서울)', value: '중앙대학교 (서울)' },
  { label: '중앙대학교 (안성)', value: '중앙대학교 (안성)' },
  { label: '중앙승가대학교', value: '중앙승가대학교' },
  { label: '중원대학교', value: '중원대학교' },
  { label: '진주교육대학교', value: '진주교육대학교' },
  { label: '진주보건대학교', value: '진주보건대학교' },
  { label: '차의과학대학교', value: '차의과학대학교' },
  { label: '창신대학교', value: '창신대학교' },
  { label: '창원문성대학교', value: '창원문성대학교' },
  { label: '청강문화산업대학교', value: '청강문화산업대학교' },
  { label: '청암대학교', value: '청암대학교' },
  { label: '청운대학교', value: '청운대학교' },
  { label: '청주교육대학교', value: '청주교육대학교' },
  { label: '청주대학교', value: '청주대학교' },
  { label: '초당대학교', value: '초당대학교' },
  { label: '총신대학교', value: '총신대학교' },
  { label: '추계예술대학교', value: '추계예술대학교' },
  { label: '춘천교육대학교', value: '춘천교육대학교' },
  { label: '춘해보건대학교', value: '춘해보건대학교' },
  { label: '충남대학교', value: '충남대학교' },
  { label: '충남도립대학교', value: '충남도립대학교' },
  { label: '충북대학교', value: '충북대학교' },
  { label: '충북도립대학교', value: '충북도립대학교' },
  { label: '충북보건과학대학교', value: '충북보건과학대학교' },
  { label: '충청대학교', value: '충청대학교' },
  { label: '칼빈대학교', value: '칼빈대학교' },
  { label: '태재대학교', value: '태재대학교' },
  { label: '평택대학교', value: '평택대학교' },
  { label: '포항공과대학교', value: '포항공과대학교' },
  { label: '포항대학교', value: '포항대학교' },
  { label: '한경국립대학교', value: '한경국립대학교' },
  { label: '한국골프과학기술대학교', value: '한국골프과학기술대학교' },
  { label: '한국공학대학교', value: '한국공학대학교' },
  { label: '한국과학기술원', value: '한국과학기술원' },
  { label: '한국관광대학교', value: '한국관광대학교' },
  { label: '한국교원대학교', value: '한국교원대학교' },
  { label: '한국기술교육대학교', value: '한국기술교육대학교' },
  { label: '한국농수산대학교', value: '한국농수산대학교' },
  { label: '한국방송통신대학교', value: '한국방송통신대학교' },
  { label: '한국복지사이버대학교', value: '한국복지사이버대학교' },
  { label: '한국성서대학교', value: '한국성서대학교' },
  { label: '한국승강기대학교', value: '한국승강기대학교' },
  { label: '한국에너지공과대학교', value: '한국에너지공과대학교' },
  { label: '한국열린사이버대학교', value: '한국열린사이버대학교' },
  { label: '한국영상대학교', value: '한국영상대학교' },
  { label: '한국예술종합학교', value: '한국예술종합학교' },
  { label: '한국외국어대학교', value: '한국외국어대학교' },
  { label: '한국전통문화대학교', value: '한국전통문화대학교' },
  { label: '한국체육대학교', value: '한국체육대학교' },
  { label: '한국침례신학대학교', value: '한국침례신학대학교' },
  { label: '한국폴리텍 I 대학 서울강서캠퍼스', value: '한국폴리텍 I 대학 서울강서캠퍼스' },
  { label: '한국폴리텍 I 대학 서울정수캠퍼스', value: '한국폴리텍 I 대학 서울정수캠퍼스' },
  { label: '한국폴리텍 I 대학 성남캠퍼스', value: '한국폴리텍 I 대학 성남캠퍼스' },
  { label: '한국폴리텍 I 대학 제주캠퍼스', value: '한국폴리텍 I 대학 제주캠퍼스' },
  { label: '한국폴리텍 II 대학 남인천캠퍼스', value: '한국폴리텍 II 대학 남인천캠퍼스' },
  { label: '한국폴리텍 II 대학 인천캠퍼스', value: '한국폴리텍 II 대학 인천캠퍼스' },
  { label: '한국폴리텍 II 대학 화성캠퍼스', value: '한국폴리텍 II 대학 화성캠퍼스' },
  { label: '한국폴리텍 III 대학 강릉캠퍼스', value: '한국폴리텍 III 대학 강릉캠퍼스' },
  { label: '한국폴리텍 III 대학 원주캠퍼스', value: '한국폴리텍 III 대학 원주캠퍼스' },
  { label: '한국폴리텍 III 대학 춘천캠퍼스', value: '한국폴리텍 III 대학 춘천캠퍼스' },
  { label: '한국폴리텍 IV 대학 대전캠퍼스', value: '한국폴리텍 IV 대학 대전캠퍼스' },
  { label: '한국폴리텍 IV 대학 아산캠퍼스', value: '한국폴리텍 IV 대학 아산캠퍼스' },
  { label: '한국폴리텍 IV 대학 청주캠퍼스', value: '한국폴리텍 IV 대학 청주캠퍼스' },
  { label: '한국폴리텍 IV 대학 충남캠퍼스', value: '한국폴리텍 IV 대학 충남캠퍼스' },
  { label: '한국폴리텍 V 대학 광주캠퍼스', value: '한국폴리텍 V 대학 광주캠퍼스' },
  { label: '한국폴리텍 V 대학 순천캠퍼스', value: '한국폴리텍 V 대학 순천캠퍼스' },
  { label: '한국폴리텍 V 대학 익산캠퍼스', value: '한국폴리텍 V 대학 익산캠퍼스' },
  { label: '한국폴리텍 V 대학 전남캠퍼스', value: '한국폴리텍 V 대학 전남캠퍼스' },
  { label: '한국폴리텍 V 대학 전북캠퍼스', value: '한국폴리텍 V 대학 전북캠퍼스' },
  { label: '한국폴리텍 VI 대학 구미캠퍼스', value: '한국폴리텍 VI 대학 구미캠퍼스' },
  { label: '한국폴리텍 VI 대학 대구캠퍼스', value: '한국폴리텍 VI 대학 대구캠퍼스' },
  {
    label: '한국폴리텍 VI 대학 영남융합기술캠퍼스',
    value: '한국폴리텍 VI 대학 영남융합기술캠퍼스',
  },
  { label: '한국폴리텍 VI 대학 영주캠퍼스', value: '한국폴리텍 VI 대학 영주캠퍼스' },
  { label: '한국폴리텍 VII 대학 동부산캠퍼스', value: '한국폴리텍 VII 대학 동부산캠퍼스' },
  { label: '한국폴리텍 VII 대학 부산캠퍼스', value: '한국폴리텍 VII 대학 부산캠퍼스' },
  { label: '한국폴리텍 VII 대학 울산캠퍼스', value: '한국폴리텍 VII 대학 울산캠퍼스' },
  { label: '한국폴리텍 VII 대학 진주캠퍼스', value: '한국폴리텍 VII 대학 진주캠퍼스' },
  { label: '한국폴리텍 VII 대학 창원캠퍼스', value: '한국폴리텍 VII 대학 창원캠퍼스' },
  { label: '한국폴리텍 특성화대학 로봇캠퍼스', value: '한국폴리텍 특성화대학 로봇캠퍼스' },
  { label: '한국폴리텍 특성화대학 바이오캠퍼스', value: '한국폴리텍 특성화대학 바이오캠퍼스' },
  {
    label: '한국폴리텍 특성화대학 반도체융합캠퍼스',
    value: '한국폴리텍 특성화대학 반도체융합캠퍼스',
  },
  { label: '한국폴리텍 특성화대학 항공캠퍼스', value: '한국폴리텍 특성화대학 항공캠퍼스' },
  { label: '한국항공대학교', value: '한국항공대학교' },
  { label: '한남대학교', value: '한남대학교' },
  { label: '한동대학교', value: '한동대학교' },
  { label: '한라대학교', value: '한라대학교' },
  { label: '한림대학교', value: '한림대학교' },
  { label: '한림성심대학교', value: '한림성심대학교' },
  { label: '한서대학교', value: '한서대학교' },
  { label: '한성대학교', value: '한성대학교' },
  { label: '한세대학교', value: '한세대학교' },
  { label: '한신대학교', value: '한신대학교' },
  { label: '한양대학교', value: '한양대학교' },
  { label: '한양대학교 (ERICA)', value: '한양대학교 (ERICA)' },
  { label: '한양사이버대학교', value: '한양사이버대학교' },
  { label: '한양여자대학교', value: '한양여자대학교' },
  { label: '한영대학교', value: '한영대학교' },
  { label: '한일장신대학교', value: '한일장신대학교' },
  { label: '협성대학교', value: '협성대학교' },
  { label: '혜전대학교', value: '혜전대학교' },
  { label: '호남대학교', value: '호남대학교' },
  { label: '호남신학대학교', value: '호남신학대학교' },
  { label: '호산대학교', value: '호산대학교' },
  { label: '호서대학교', value: '호서대학교' },
  { label: '호원대학교', value: '호원대학교' },
  { label: '홍익대학교 (서울)', value: '홍익대학교 (서울)' },
  { label: '홍익대학교 (세종)', value: '홍익대학교 (세종)' },
  { label: '화성의과학대학교', value: '화성의과학대학교' },
  { label: '화신사이버대학교', value: '화신사이버대학교' },
];
